### ISSUE TITLE
created_at, updated_at を<yyyy-MM-ddTHH:mm:ss>形式（LocalDateTime）で返したい

### ISSUE THREAD

**Issue by kitamuraDev** [kitamuraDev/reminder-app-backend#1]
### OpenAPI 3.0 のスキーマ定義

```yaml
createdAt:
  type: string
  format: date-time
updatedAt:
  type: string
  format: date-time
```

### 課題点

上記のスキーマ定義だと生成されるフィールド変数の型が`OffsetDateTime`になる。
OffsetDateTimeでは、以下のようなフォーマットになり、データ整形が面倒。なるべくDBから取ってきたデータをそのまま返したいので可能ならOffsetDateTimeでは扱いたくない

```
2023-09-20T23:09:17.592551+09:00
```

### 現状（とりあえず）

まずは作り上げたいので、created_at, updated_at は created_on, updated_on にして、日付だけを持つようにする。データ型は`LocalDate`になる。
